version = 0.1

[default]
[default.global.parameters]
stack_name = "enfin-ai-document-extraction-stack"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
resolve_s3 = true
resolve_image_repos = true
s3_prefix = "enfin-ai-document-extraction-stack"
region = "us-west-2"
image_repositories = []

[Dev.deploy.parameters]
stack_name = "enfin-ai-document-extraction-stack"
resolve_s3 = true
s3_prefix = "enfin-ai-document-extraction-stack"
resolve_image_repos = true
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
disable_rollback = true
parameter_overrides = "Environment=\"Dev\" S3BucketName=\"enfin-milestone-docs-dev\" AutoAcceptThreshold=\"0.95\" FlagThreshold=\"0.80\" ExtractionModel=\"us.meta.llama4-maverick-17b-instruct-v1:0\" ModelMaxTokens=\"4096\" ModelTemperature=\"0.1\" MaxImagesPerLLMCall=\"3\" OCREngine=\"rapidocr\" OCRLang=\"en\" ForceOCR=\"true\" PDFImageDPI=\"300\" MaxImageDimension=\"2000\" OutputSQSDelaySeconds=\"300\" ConfigCacheTTLSeconds=\"300\" SalesforceEnabled=\"false\" SalesforceTokenTableName=\"\" SalesforceHost=\"\" SalesforceInstanceUrl=\"\" SalesforceUsername=\"\" SalesforceSecretName=\"\" SalesforceApexPath=\"\" Timezone=\"US/Pacific\" TimestampFormat=\"%m-%d-%Y\" LogLevel=\"INFO\" NomalizationRuleReplacements=\"{\\\" \\\": \\\"\\\",\\\"-\\\": \\\"\\\",\\\"&amp;\\\": \\\"&\\\"}\""

[Dev-v1.deploy.parameters]
stack_name = "enfin-ai-document-extraction-stack"
resolve_s3 = true
s3_prefix = "enfin-ai-document-extraction-stack"
resolve_image_repos = true
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Environment=\"Dev-v1\" S3BucketName=\"enfin-milestone-docs-dev-v1\" AutoAcceptThreshold=\"0.9\" FlagThreshold=\"0.8\" ExtractionModel=\"us.meta.llama4-maverick-17b-instruct-v1:0\" ModelMaxTokens=\"4096\" ModelTemperature=\"0\" MaxImagesPerLLMCall=\"3\" OCREngine=\"rapidocr\" OCRLang=\"en\" ForceOCR=\"true\" PDFImageDPI=\"300\" MaxImageDimension=\"2000\" ConfigCacheTTLSeconds=\"300\" SalesforceEnabled=\"true\" SalesforceTokenTableName=\"Token_Management_Dev\" SalesforceHost=\"https://enfincorp--upgradeorg.sandbox.my.salesforce.com/services/\" SalesforceInstanceUrl=\"https://enfincorp--upgradeorg.sandbox.my.salesforce.com/services/\" SalesforceUsername=\"api.integration@enfin.upgradeorg.com\" SalesforceSecretName=\"EnFin_SF_Factory_UpgradeOrg\" SalesforceApexPath=\"apexrest/AWSDocumentExtractionController\" SalesforceDiffTime=\"1800\" SalesforceAuthPath=\"oauth2/token\" Timezone=\"US/Pacific\" TimestampFormat=\"%m-%d-%Y\" LogLevel=\"INFO\" NomalizationRuleReplacements=\"{\\\" \\\": \\\"\\\",\\\"-\\\": \\\"\\\",\\\"&amp;\\\": \\\"&\\\"}\" AggregationEnabled=\"true\""
